// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXaE2eP-rX_JzQhJKRItWsTWhvVX722As',
    appId: '1:374061908694:web:b8c46c1122f4cafb7a7f77',
    messagingSenderId: '374061908694',
    projectId: 'nativeapp-a1308',
    authDomain: 'nativeapp-a1308.firebaseapp.com',
    storageBucket: 'nativeapp-a1308.appspot.com',
    measurementId: 'G-TWB4RQSQ76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_E_i-8e2TFe6g_3g4BA0m_E9mb21BoXg',
    appId: '1:374061908694:android:e2ce4d607178bd2c7a7f77',
    messagingSenderId: '374061908694',
    projectId: 'nativeapp-a1308',
    storageBucket: 'nativeapp-a1308.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCluFt_DlnjKKVuEUE_DgpR1DInyvqxCio',
    appId: '1:374061908694:ios:eb8985ff6529e37b7a7f77',
    messagingSenderId: '374061908694',
    projectId: 'nativeapp-a1308',
    storageBucket: 'nativeapp-a1308.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCluFt_DlnjKKVuEUE_DgpR1DInyvqxCio',
    appId: '1:374061908694:ios:9abc247200fc450a7a7f77',
    messagingSenderId: '374061908694',
    projectId: 'nativeapp-a1308',
    storageBucket: 'nativeapp-a1308.appspot.com',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXaE2eP-rX_JzQhJKRItWsTWhvVX722As',
    appId: '1:374061908694:web:5ab2a20c3085188f7a7f77',
    messagingSenderId: '374061908694',
    projectId: 'nativeapp-a1308',
    authDomain: 'nativeapp-a1308.firebaseapp.com',
    storageBucket: 'nativeapp-a1308.appspot.com',
    measurementId: 'G-BC0HFTJB0H',
  );

}